research_task:
  description: >
    Conduct a thorough research about {topic}. Make sure you find any interesting and relevant information given the current year is 2024.
    The research should be in {language}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic} in markdown format.
    Make sure to find enough information, so you could write a blog post about it.
  agent: researcher

write_blog_post:
  description: >
    Write a blog post about {topic} based on the findings of the research you've conducted.
    As it needs to be an interesting read, don't create too many short chapters that break the flow of the text.
    Try to tell a story that is easy to understand and follow.
    Ensure that the post is written in a clear and concise manner that is easy to understand.
    Try to put information in context or a relatable example, so the user can understand the information better.
    Try to incorporate the authors thoughts in the post: {description}
    The language should be {language}.
    Consider the target audience: {target_audience}.
  expected_output: >
    A blog post with a maximum of 1500 words in markdown format
  agent: blog_writer

write_twitter_post:
  description: >
    Write Twitter copy about {topic} based on the research you've conducted and the blog post you've written.
    Try to incorporate the authors thoughts in the post: {description}
    The copy should be a concise message that is maximum 280 characters.
    The language should be {language}.
    Consider the target audience: {target_audience}.
  expected_output: >
    A Twitter post with a maximum of 280 characters
  agent: social_media_manager

write_linkedin_post:
  description: >
    Task Input:
    Write LinkedIn copy about {topic} based on the research you've conducted and the blog post you've written.
    Try to incorporate the authors thoughts in the post: {description}
    Styling Guide:
    The copy should be a concise message that is maximum 3000 characters.
    Make use of emojis (only in the beginning of each paragraph) and hashtags (at the end of the post).
    The language should be {language}.
    Consider the target audience: {target_audience}.
  expected_output: >
    A LinkedIn post with a maximum of 3000 characters
  agent: social_media_manager