research_task:
  description: >
    Conduct comprehensive research on {topic}, focusing on relevant and up-to-date information given the current year (2024). Prioritize reputable sources and ensure the research addresses any recent developments or trends. The research should be conducted in {language}.
  expected_output: >
    Provide a list of 10 well-researched bullet points that summarize the most critical information about {topic} in markdown format. Each bullet point should be detailed enough to support the writing of a blog post, including references to sources where applicable. Highlight key insights or trends and consider gaps or areas of uncertainty in the current understanding of {topic}.
  agent: researcher

write_blog_post:
  description: >
    Write a well-structured blog post about {topic}, using the findings from your research. Ensure the post is engaging, with a logical flow between sections. Avoid overly short chapters that break the flow of the narrative. Focus on storytelling, making the content relatable by providing examples or context that enhances understanding. 
    Incorporate the author's perspective: {description}, and ensure the post aligns with the intended audience: {target_audience}. The language should be {language}.
  expected_output: >
    A polished blog post in markdown format, not exceeding 1500 words, with a clear introduction, main body, and conclusion. Ensure readability by including headings, subheadings, and smooth transitions between sections. The post should be informative, engaging, and include relevant links or references where applicable.
  agent: blog_writer

write_twitter_post:
  description: >
    Write a concise Twitter post (maximum 280 characters) about {topic}, using insights from your research and blog post. The message should be engaging and highlight key takeaways in a way that encourages interaction (e.g., retweets, likes, comments). Incorporate the author thoughts: {description} and ensure the copy resonates with the target audience: {target_audience}. The language should be {language}.
  expected_output: >
    A Twitter post in markdown format, not exceeding 280 characters. The post should include one or two relevant hashtags to enhance discoverability and, if appropriate, a link to the blog post or related content.
  agent: social_media_manager

write_linkedin_post:
  description: >
    Create a LinkedIn post (maximum 3000 characters) that summarizes key insights from your research and blog post about {topic}. Ensure the tone is professional but engaging, incorporating the author's perspective: {description} and tailoring the message to the platform's target audience: {target_audience}. 
    Follow LinkedIn best practices by starting each paragraph with a relevant emoji and concluding the post with appropriate hashtags. The language should be {language}.
  expected_output: >
    A LinkedIn post in markdown format, with a maximum of 3000 characters. The post should be structured with a strong opening hook, informative paragraphs, and a clear call-to-action. Include up to three emojis at the beginning of paragraphs and relevant hashtags at the end.
  agent: social_media_manager